### ISSUE TITLE
大佬，请问Copilot在idea端的那种代码补全方式是怎么实现的

### ISSUE THREAD

**Issue by Feng93** [git-cloner/codegeeker#2]
rt，如在editor中实时预览代码，按TAB进行应用

**Comment by little51** [comment]
抱歉，具体的我也没研究过，不过肯定不是用vscode的Extension方式实现的，因为Extension方式不支持流式返回数据，只能等待全部结果生成后才一次性返回，这样体验特别不好，所以我用Extension做了一段时间也就放弃了。另外，补全这种推理方法，响应要求非常高，对硬件要求也很高。
